name: Run Scheduler Every 30 Mins

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:  # Manual trigger ke liye

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Puppeteer Browser
        run: npx puppeteer browsers install chrome  # Puppeteer ka Chrome install karega

      - name: Run Script
        run: node index.js  # Tumhara script execute hoga
